# Generated by CodiumAI
""" This module contains tests for the data_split.py module. """

from scripts.data_split import split_data
from tsmixer.data_load import load_data


class TestSplitData:
    """Tests for the split_data function."""

    # Correctly splits data into train, test, and validation sets
    def test_correct_split(self):
        """Test that the function correctly splits the data."""
        ds = load_data("mik3ml/timeseries-finance-ETF")
        train, test, validation = split_data(ds)

        assert len(train) == 80
        assert len(test) == 10
        assert len(validation) == 10
